### ISSUE TITLE
bug: 利用api生成一个user后报错

### ISSUE THREAD

**Issue by carlSunLiang** [tuateam/tua-api#26]
**版本**
Version [e.g. 0.1.0]

**描述一下 bug**
 就是脚手架生成的项目，利用api生成一个user, 引入之后，编译没有问题，但是在小程序开发工具上报错
**复现 bug**
复现的步骤：

1. 首先
![image](https://user-images.githubusercontent.com/8129970/54606706-8a217680-4a87-11e9-92db-c1463ef661a7.png)
![image](https://user-images.githubusercontent.com/8129970/54606722-91e11b00-4a87-11e9-8ae5-7d47b2add74c.png)

2. 看到了错误
![image](https://user-images.githubusercontent.com/8129970/54606443-d02a0a80-4a86-11e9-8603-e8d350d5776a.png)

如果方便的话：

* 复现 bug 的在线地址：
  * codepen: https://codepen.io/
  * jsfiddle: https://jsfiddle.net/
  * codesandbox: https://codesandbox.io/
* 复现 bug 的仓库地址：https://github.com/new

**预期行为**
简洁清晰地描述一下预期行为。

**附加上下文**
添加一些问题的相关上下文。

**Comment by BuptStEve** [comment]
给个复现的代码仓库地址吧

**Comment by carlSunLiang** [comment]
<config>
{
    "navigationBarTitleText": "点击空白处跳转",
    "usingComponents": {
        "TestComp": "./comps/TestComp/TestComp"
    }
}
</config>

<template lang="wxml">
    <view class="container" catchtap="gotoLogs">
        <button type="primary" catchtap="gotoTodos">
            点我去 todos 页面
        </button>

        <TestComp
            propA="{{ msg }}"
            propB="{{ a.b }}"
        />

        <view class="box">msg: {{ msg }}</view>
        <button type="primary" size="mini" catchtap="tapMsg">
            this.msg += n++
        </button>

        <view>a.b: {{ a.b }}</view>
        <button type="primary" size="mini" catchtap="tapAB">
            this.a.b += n++
        </button>

        <view>arr: {{ arr }}</view>
        <button type="primary" size="mini" catchtap="tapArr">
            this.arr.push(n++)
        </button>
        <button type="primary" size="mini" catchtap="unshiftNested">
            this.arr.unshift({ c: { d: 'hey' } })
        </button>

        <view>arr[0].c.d: {{ arr[0].c.d }}</view>
        <button type="primary" size="mini" catchtap="tapArrNest0">
            this.arr[0].c.d = n++
        </button>

        <view>arr[1].c.d: {{ arr[1].c.d }}</view>
        <button type="primary" size="mini" catchtap="tapArrNest1">
            this.arr[1].c.d = n++
        </button>

        <view>arr[1]: {{ arr[1] }}</view>
        <button type="primary" size="mini" catchtap="tapArrSp">
            this.arr.splice(2, 2, n++)
        </button>

        <view>------ computed ------</view>
        <view>g: {{ g }}</view>
        <view>reversedG: {{ reversedG }}</view>
        <button type="primary" size="mini" catchtap="tapReverseG">
            this.g = this.reversedG
        </button>

        <view>a.b: {{ a.b }}</view>
        <view>gAndAB: {{ gAndAB }}</view>
        <view>dataAndComputed: {{ dataAndComputed }}</view>
        <button type="primary" size="mini" catchtap="tapAB">
            this.a.b = 'a.b' + n++
        </button>
    </view>
</template>

<script>
import { log } from '@utils'
import { userApi } from '@/apis/'

let n = 0

export default {
    data () {
        return {
            msg: 'msg',
            a: {
                b: 'a.b',
            },
            arr: [
                { c: { d: 'd0' } },
                { c: { d: 'd1' } },
                1, 2, 3,
            ],
            g: 'hello world',

            // 测试所需数据
            testData: {
                nested: {
                    steve: 'steve',
                    young: {
                        young: 'young',
                    },
                },
                arr: [],
                nestedArr: [
                    {
                        name: 'steve',
                        nick: {
                            young: 'young',
                        },
                    },
                    {
                        name: 'jame',
                    },
                ],
                insertNestedArr: [],
            },
        }
    },
    created () {
        log(this)
        /* eslint-disable no-global-assign */
        global = this
        /* eslint-enable no-global-assign */
        log('userApi')
        console.log(userApi)
        log('userApi')
        userApi({ a: '1', b: '2' }).then(console.log).catch(console.error)       // 收到响应
             

        for (let i = 100; i > 90; i--) {
            this.g = i
            this['g'] = i + 1
        }
    },

    computed: {
        reversedG () {
            return this.reverseStr(this.g)
        },
        gAndAB () {
            return this.g + ' + ' + this.a.b
        },
        dataAndComputed () {
            return this.g + ' + ' + this.reversedG
        },
    },
    watch: {
        msg (newVal, oldVal) {
            log(`msg: ${oldVal} -> ${newVal}`)
        },
        'a.b' (newVal, oldVal) {
            log(`a.b: ${oldVal} -> ${newVal}`)
            setTimeout(() => {
                this.msg = this.reverseStr(this.msg)
            }, 1000)
        },
        'g' (newVal, oldVal) {
            log(`g: ${oldVal} -> ${newVal}`)
        },
        'reversedG' (newVal, oldVal) {
            log(`reversedG: ${oldVal} -> ${newVal}`)
        },
        'gAndAB' (newVal, oldVal) {
            log(`gAndAB: ${oldVal} -> ${newVal}`)
        },
    },
    methods: {
        tapMsg () {
            this.msg += n++
        },
        tapAB () {
            this.a.b += n++
        },
        tapArr () {
            this.arr.push(n++)
        },
        tapArrNest0 () {
            this.arr[0].c.d = n++
        },
        tapArrNest1 () {
            this.arr[1].c.d = n++
        },
        tapArrSp () {
            this.arr.splice(2, 2, n++)
        },
        tapReverseG () {
            this.g = this.reversedG
        },
        reverseStr (str) {
            return String(str).split('').reverse().join('')
        },
        unshiftNested () {
            this.arr.unshift({ c: { d: 'hey' } })
        },
        gotoLogs () {
            wx.navigateTo({ url: '/pages/logs/logs' })
        },
        gotoTodos () {
            wx.navigateTo({
                url: '/pages/todos/todos',
            })
        },
    },
}
</script>

<style lang="less">

</style>
就是脚手架直接生成的demo ，然后 api工具生成一个user的api,其他都没有改，直接引用，编译没有问题

**Comment by BuptStEve** [comment]
一眼看过去应该是 `userApi` 用错了，应该是 `userApi.foo({ ... })`。 
`foo` 是接口名称

参考下这个 https://codesandbox.io/s/2o24xn0750

**Comment by carlSunLiang** [comment]
![image](https://user-images.githubusercontent.com/8129970/54608424-9c9daf00-4a8b-11e9-9451-5c3f35086a56.png)
没太明白 为啥有这个repos()执行之后才有实例吗，我觉得您最好在文档里说明一下。我感觉有点懵，但是整个tua-mp设计思想挺好的，就是文档的，，，

**Comment by BuptStEve** [comment]
你没明白 api 如何抽象和配置。举例来说

* `https://api.github.com/search/users?q=${name}`
* `https://api.github.com/search/repositories?q=${name}`

这俩 api 都有公共前缀 `search` 所以都属于 `searchApi`。所以相当于抽象成了

* `searchApi.users`
* `searchApi.repositories` （这个有点长，所以重命名成 `repo`）

所以应该这么调用

```js
searchApi.users().then(console.log).catch(console.error)

async () => {
  const data = await searchApi.repo()
  ...
}
```

配置如下所示

```js
export default {
  prefix: 'search',
  pathList: [
    // docs: https://developer.github.com/v3/search/
    // example: https://api.github.com/search/users?q=${name}
    { path: 'users', params: { q: 'BuptStEve' } },
    // docs: https://developer.github.com/v3/search/#search-repositories
    // example: https://api.github.com/search/repositories?q=${name}
    {
      path: 'repositories',
      name: 'repos',
      params: { q: 'storage', sort: 'stars' },
    },
  ],
}
```
