### ISSUE TITLE
feat: 支持 FormData 类型的接口请求

### ISSUE THREAD

**Issue by qinmengjiao** [tuateam/tua-api#32]
**你的功能请求是否与某些问题相关？请描述**
目前仅支持字符串类型的接口请求，如果需要通过 axios 发送 FormData 数据需要这么写

```js
const formData = new FormData()

imgUploadApi.userUpload(null, { 
    reqFnParams: { reqParams: formData },
    axiosOptions: {
        transformRequest: null,
        headers: { 'Content-Type': 'multipart/form-data' },
    },
})
```

**描述您想要的解决方案**
假如 api 接收的数据是 FormData 类型，则按照以下方式调用即可

```js
imgUploadApi.userUpload(formData)
```

**Comment by BuptStEve** [comment]
看了下源码可以不用设置 headers
https://github.com/axios/axios/blob/503418718f669fcc674719fd862b355605d7b41f/lib/adapters/xhr.js#L15-L17
